version: '3'

services:
  flaskapp:
    build: ./flask_registration
    ports:
      - "8000:8000"
    network_mode: host

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: nginx
    environment:
      - SERVER_NAME=3.92.134.21
    restart: always 
    network_mode: host
    

